# Generated by Django 4.0.1 on 2022-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sud_actividad',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sud_actividad',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sud_actividad',
            name='fecha_real',
            field=models.DateField(),
        ),
    ]
