# Generated by Django 4.0.1 on 2022-03-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_sud_actividad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('nivel1', 'Puede ver contenido agregarlo pero no eliminarlo'),)},
        ),
    ]
